Docker Cleanup

diff --git a/.github/workflows/docker-cleanup.yml b/.github/workflows/docker-cleanup.yml
--- a/.github/workflows/docker-cleanup.yml
+++ b/.github/workflows/docker-cleanup.yml
@@ -3,8 +3,6 @@ name: Docker Cleanup
 on:
   schedule:
     - cron: '0 0 * * 1' # ירוץ פעם בשבוע ביום שני
-  workflow_dispatch:  # הוספת האפשרות להריץ ידנית
-
 jobs:
   cleanup:
     runs-on: ubuntu-latest
@@ -13,7 +11,7 @@ jobs:
         run: sudo apt-get update && sudo apt-get install -y jq
 
       - name: Log in to DockerHub
-        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
 
       - name: Remove old Docker images locally
         run: docker image prune -af  # מוחק תמונות שלא בשימוש
@@ -23,12 +21,23 @@ jobs:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
           DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
         run: |
+          # התחברות ל-Docker Hub וקבלת הטוקן
           TOKEN=$(curl -s -X POST -H "Content-Type: application/json" \
             -d "{\"username\": \"$DOCKERHUB_USERNAME\", \"password\": \"$DOCKERHUB_PASSWORD\"}" \
             https://hub.docker.com/v2/users/login/ | jq -r .token)
 
+          # הדפסת הטוקן לצורך בדיקה
+          echo "Token: $TOKEN"
+
+          # אם הטוקן לא קיים, להפסיק את הביצוע
+          if [ "$TOKEN" == "null" ] || [ -z "$TOKEN" ]; then
+            echo "Error: Unable to get DockerHub token"
+            exit 1
+          fi
+
           REPO="romliani/devops-project-flask"
 
+          # קבלת רשימת התגים בתמונות
           IMAGES=$(curl -s -H "Authorization: Bearer $TOKEN" \
             "https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=100" | jq -r '.results | map(select(.name != "latest")) | .[].name')
 
